### ISSUE TITLE
如何让用户自定义字段名及对应的字段值？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/super-tag#11]
如果用户可以简单轻松地自定义一些字段名及对应的字段值来选择，那么这个插件将变得更有用。而且可以考虑改名为超级表单插件。我感觉只用来实现任务管理还没有真正发挥出其功能来。

我再仔细看看文档，看能不能找出自定义的方法来。

**Comment by dongrentianyu** [comment]
而且和aggregation插件同样的问题是，需要都带上一个超级插件，比如“task”，然后才能显示表单，我感觉这个可以改成筛选器，但我看论坛上的讨论，好像是当时没写出来，然后就用js去写了。总之先记录下来。因为我觉得比其重复使用单个标签，还是筛选器的范围要更大一些。而且也就能尽可能避免无效标签了。

**Comment by dongrentianyu** [comment]
看了一点[Schema](https://json-schema.org/)的文档，大概学会了其中的架构。但有一个问题是，其值基本上是写定的。能不能改成另一个插件那样，筛选出某一字段所有的字段值。不过看上去应该挺难做到。但如果是类似ehcarts图表那样生成的，应该也不能实现的样子。试试好了。

**Comment by dongrentianyu** [comment]
还有一个奇怪的问题，就是我在原来的schema中加入一些新字段后，原来的条目依然只能显示之前有的字段内容。只有在去除标签后重新添加标签才能显示正常的内容来。

![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/08215af1-09b0-409b-8682-ff50efe07159)

这是原来的条目，但实际上我加入了一些新字段内容。比如date时间选项。

![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/6d889bec-33ba-4dfa-9758-a49fd081fef8)

但只有后面新建的条目才能正常显示出来。去除再添加标签后就能正常显示出来了。

![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/55c8a892-85e7-454f-ac55-53420d26ead1)

**Comment by dongrentianyu** [comment]
一个好奇的问题，就是在schema字段里，有写一些字段是required的，但新建条目后并不会显示出来。

![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/c87ff36f-3ceb-42e3-a06f-659394118e61)

我想的是在新建条目后，因为代码里写了`"required": ["completed"]`，那应该就会列出completed字段来选择。不然就没必要写这个required了。

**Comment by dongrentianyu** [comment]
> 看了一点[Schema](https://json-schema.org/)的文档，大概学会了其中的架构。但有一个问题是，其值基本上是写定的。能不能改成另一个插件那样，筛选出某一字段所有的字段值。不过看上去应该挺难做到。但如果是类似ehcarts图表那样生成的，应该也不难实现的样子。试试好了。

简单尝试了一下，筛选器不好写。因为有`”`特殊符号，增加前后缀会使筛选器失效，暂时先放弃。

**Comment by dongrentianyu** [comment]
https://github.com/tiddly-gittly/super-tag/issues/11#issuecomment-1611751708

这个我已经看到了required必须是一个数组，且为字符串类型。然后值必须是独一无二的，不能重复，然后格式我也注意到了。但还是没有正常新建条目时展示内容。

```
{
    "type": "object",
    "properties": {
        "姓名": {
            "type": "string"
        },
        "author": {
            "type": "string",
            "enum": [
                "男",
                "女"
            ]
        },
        "tmo_taskState": {
            "type": "string",
            "description": "任务的状态",
            "enum": [
                "New",
                "Running",
                "Completed",
                "Archived",
                "Terminated",
                "Suspended"
            ]
        }
    },
   "required": [
            "tmo_taskState"
        ],
        "defaultProperties": [
            "tmo_taskState"
        ]
    }
```

代码如上，但还是不能正常显示。

我把意义之塔里的代码复制过去也不能实现，还是说有什么全局设置没看到。

**Comment by dongrentianyu** [comment]
这样的话，新建条目还得是自己做一个按钮，而不是简单地打上标签。虽然做一个按钮也挺简单的。

**Comment by dongrentianyu** [comment]
用list筛选出字段值估计不太可能，先关闭了，等后面看有机会能不能实现一下。

**Comment by linonetwo** [comment]
> 还有一个奇怪的问题，就是我在原来的schema中加入一些新字段后，原来的条目依然只能显示之前有的字段内容。只有在去除标签后重新添加标签才能显示正常的内容来。

这个应该是性能优化了，其实关闭这个条目重新打开就好了

**Comment by linonetwo** [comment]
> 也就是说，如果我需要直接展示特定内容的话，我就需要在新建这个条目的时候直接把要展示的字段名称带上

这样没错啊，不然一开始就一大堆列在下面就太长了。现在只装了一个任务相关的超级标签，之后可能会有一大堆，加起来可能100多个，那全列在下面都超出天际了。

**Comment by linonetwo** [comment]
> 不然就没必要写这个required了。

不过一开始是想做成这个功能的，但不知道为啥现在没生效，可能是还得修一下js部分吧。

**Comment by dongrentianyu** [comment]
> > 也就是说，如果我需要直接展示特定内容的话，我就需要在新建这个条目的时候直接把要展示的字段名称带上
> 
> 这样没错啊，不然一开始就一大堆列在下面就太长了。现在只装了一个任务相关的超级标签，之后可能会有一大堆，加起来可能100多个，那全列在下面都超出天际了。

我是想有一些必须要填的展示出来。一些可选的由用户点击展示。必须要填的就会用到required了。在required里填写那些字段是一定要填写的。现在就是在required里填写了，但不会展示出来。

**Comment by linonetwo** [comment]
新版 itkg 带的 tmo 拆成独立的插件了，删去了一些用不到的字段
