### ISSUE TITLE
展示成表格可能会更好一点？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/super-tag#14]
![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/2583cb26-b66b-4274-b1d4-c559873dd842)

类似图片里库克马插件的形式。

**Comment by linonetwo** [comment]
这右边太多空白浪费了，现在至少横着堆满了

**Comment by linonetwo** [comment]
我们尽量去参考 Tana 的 supertag 的样式

**Comment by dongrentianyu** [comment]
我去看看tana是怎么做的。

**Comment by dongrentianyu** [comment]
想到了可以做成放在副标题的方式。类似[xp中的做法](https://keatonlao.github.io/tiddlywiki-xp/#%24%3A%2Fgtd%2F20220627091713462)。

对于选择性质的比较好处理，或者按钮什么的，但对于要输入文本的，就不太好。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/c87c099e-cec2-4e1a-88bb-706da72f3505)


另一个问题是，如果太多了，也不好。像我用supertag，一般都有十来个选项的。可能还是没有特别好的解决办法。
