### ISSUE TITLE
网站内容没有更新过去？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/super-tag#15]
挺奇怪，网站内容还是英文，检查发现里面没有更新的中文内容。

**Comment by linonetwo** [comment]
我重新运行了action，还没有吗

**Comment by dongrentianyu** [comment]
对，仍然没有。

**Comment by dongrentianyu** [comment]
我强制刷新了，仍然没有更新过去。但仓库里的条目是有中文翻译的。挺奇怪。

**Comment by dongrentianyu** [comment]
好像是只运行了插件的actions，没有运行wiki的actions。你可以改一下wiki里的条目，看看wiki里的actions有无正常运行。
