### ISSUE TITLE
如何改进时间格式的编辑体验

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/super-tag#21]
![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/5ee889df-173b-41a0-8c43-8bb5161997f1)

如何改进这类时间格式的编辑体验？因为鼠标老是滑不到我要选择的内容。滑过去了又要再滑过来，要浪费不少时间，而且特别容易心态爆炸。

我在网上找不到可以直接在shcema字段里填写选择样式的。

目前是需要返回像17：30这样的数据，因为后面还需要依赖这个排序。

**Comment by dongrentianyu** [comment]
kixam/TW5-datepicker插件编辑体验也不好，选半天选不出来。可能得单独找一下如何定义了。

**Comment by dongrentianyu** [comment]
好吧，直接用太微原生态都还能接受。先用着。

```
<$edit-text tiddler="AppSettings" field="myconfig" type="time"/>
```

**Comment by dongrentianyu** [comment]
不过我好奇这两个实现起来不应该是一样的效果的吗？虽然太微原生态的稍微好一点点。不知道咋让选择起来更简单，更流利顺畅。

**Comment by dongrentianyu** [comment]
好吧，是我鼠标问题。鼠标本身就不太灵敏，我还把滑动一次行数改成了4，怪不得我每次都选不到。有时候真觉得自己挺愚蠢的。

**Comment by linonetwo** [comment]
这个UI很落后，我在react里会用那种轮盘形状的
