### ISSUE TITLE
翻译问题：是否应该根据不同语言配套不同字段内容？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/super-tag#9]
![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/b5d377b4-d39e-472c-837b-66b46b68b17e)

平时使用过程中，看着这么多字段，但是单词不认识。虽然我知道去查单词就可以了解，但我想，是不是根据不同语言配套不同的字段内容会更好？

从用户体验上，看见用不上的字段和不理解的内容，就感觉这个东西好难，不会用啊。

**Comment by dongrentianyu** [comment]
我看上面有任务的状态，那其他字段应该也要这样标明一下。字段名和字段值的解释可以做一个条目，然后放在打开或展示的按钮旁边，方便跳转过去查看。

还有涉及到一些时间的字段，应该用更方便的方式输入。

**Comment by dongrentianyu** [comment]
我用`pnpm i`安装，然后`pnpm dev`，结果卡住了。

![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/b9f8ae1a-60f4-46c3-aefa-51ca5fadbc99)

然后我`npm i`，试了一遍。一直卡着。

后面运行了一下就发现跟上面一样报错了。

用vs code打开是一片红，我也不知道是为什么。

![image](https://github.com/tiddly-gittly/super-tag/assets/109711900/e7f52e97-b7d0-42d9-af1c-81004d289404)

**Comment by linonetwo** [comment]
我这可以启动，可能是因为之前的框架没有适配 Windows 导致的，我换成 modern 框架试试

<img width="759" alt="截屏2023-06-22 21 42 02" src="https://github.com/tiddly-gittly/super-tag/assets/3746270/b70ce908-6e97-42e5-88c7-c23f23379222">

**Comment by linonetwo** [comment]
好了，我重构成用 modern.dev 了，开发速度变快，而且应该也支持 window 了

**Comment by dongrentianyu** [comment]
那应该怎么安装启动呢？我用`pnpm i`和`pnpm run dev`都不成功。用`npm run dev`也不成功。

**Comment by dongrentianyu** [comment]
其他in-tagging-tree仓库也类似这样，不知道怎么打开。

**Comment by linonetwo** [comment]
反正不行就删掉 node_modules 再 pnpm i

**Comment by dongrentianyu** [comment]
不同语言的不同字段内容估计只能让用户自己定义了。我把翻译的文档提交过去。等下就pr上去。

**Comment by linonetwo** [comment]
我觉得还是最好一个匹马能对应各种不同的翻译，然后通过翻译插件来提交这个我还没想好怎么搞，最近也没空去想这个了。

**Comment by dongrentianyu** [comment]
我想了想，应该在ViewTemplate下处理，做两个，一个是英文原版的，另一个是中文的。中文的字段名称与英文的保持不变，但字段值翻译一下。因为字段名称可以通过description来翻译显示。同时又不至于搞成多个不同的字段内容。

然后在ViewTemplate里通过语言来筛选，或者让用户来解决使用何种方式。

当然如果不这样做的话，那就是写个列表，列出这些单词的意思。

**Comment by linonetwo** [comment]
这应该是在 react 里写的，所以应该是在 react 里读当前语言、找语言包来展示吧
